### ISSUE TITLE
description of the configuration 

### ISSUE THREAD

**Issue by bertvannuffelen** [semagrow/semagrow#12]
Dear,

where do I find documenation of the impact of the configuration and the behaviour of the federation engine?

I only find a reference to a VoID file as the source description but not a description that indicates what is mandatory versus optional, and what the effect of other information is.

kr,

Bert

**Comment by gmouchakis** [comment]
Hi Bert,

the documentation for the configuration can be found at http://semagrow.github.io/configuration/. As stated there, to prepare the metadata.ttl file you can use either Eleon or sevod-scraper. I recommend using sevod-scraper because it will automatically create the configuration file for you.

King regards,
Giannis.

**Comment by stasinos** [comment]
Dear Bert,
Has the answer addressed the issue or do you need more clarifications?
s
